### ISSUE TITLE
Should tl::expected be nodiscard?

### ISSUE THREAD

**Issue by olson-dan** [TartanLlama/expected#47]
I'm guessing that this is maybe controversial in the wider community, but I'm looking into adopting `tl::expected` and I'm not quite sure why it's not [[nodiscard]], is there a reason for this?

**Comment by TartanLlama** [comment]
Mostly just that the paper isn't `[[nodiscard]]`. And since it's a vocabulary type I don't want to be too opinionated about it. If you want it to be nodiscard it should be a simple edit.

**Comment by SirPolly** [comment]
If you are not using the result of a function, why would you care about an error? Except with expected<void, ...> maybe.

**Comment by hwelzel** [comment]
Hi, thanks for this amazing (and lightweight) library.

I just found this and thought I'd share one bug I had for a while.

    const auto transform = [](const auto& input) -> tl::expected<output> {
        if (!input) {
            input.error();
        }
        return output{input->...};
     };

Clearly the if is wrong. I should've used `return tl::make_unexpected(input.error())` instead. The next line was UB.
Obviously the real fix to this bug was to rearrange the lambda and use .map() instead which I did.

`const auto transform = [](const auto& input) { return output{input...}; };`
`const auto out = in.map(transform);`

But I just wanted to note that if [[nodiscard]] was used for .error() this wouldn't even have compiled. :)
